### ISSUE TITLE
Services in the SGID folder on mapserv

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#32]
- CountyBoundaries
- DOGM
- LandOwnership

We should have descriptions on these services that describe their purpose. I believe that Michael may know about them.

**Comment by stdavis** [comment]
Hey @MichaelAGRC: Do you know anything about these services? http://mapserv.utah.gov/arcgis/rest/services/SGID

**Comment by steveoh** [comment]
These will be easy to convert with forklift. @MichaelAGRC will you give us an update on what the purpose of these features are. Thanks!

**Comment by MichaelAGRC** [comment]
I really don't know.  Are they in use?  Are they used in any other services?  It's been a long time since I set up any services on mapserv.

**Comment by steveoh** [comment]
I thought they were setup for some arcgis online purpose.

Yes they are in use:
![image](https://cloud.githubusercontent.com/assets/325813/16632769/f496edec-4382-11e6-9362-63a6ea3d3c8b.png)
![image](https://cloud.githubusercontent.com/assets/325813/16632759/e050a27e-4382-11e6-8c25-1c14d46867b8.png)

Services cannot be used inside of other services so we can rule that out.

**Comment by MichaelAGRC** [comment]
Is that for all services on mapserv, including the basemaps?

**Comment by steveoh** [comment]
no @MichaelAGRC, that chart is only showing data for the 3 services we are referencing in this issue.

**Comment by MichaelAGRC** [comment]
Okay.  I've looked pretty extensively in AGOL, and can't really find what would be using those services from AGOL side.  I found one for DOGM that AGOL says hasn't been hit in over 6 months.  County Boundaries is a hosted feature service, so not reading from mapserv.  We should be having folks use the SITLA services for Land Ownership.  We don't have a Land Ownership layer that I can find in AGOL right now.  Unless we have info otherwise, I'd be inclined to say that the requests are not coming from AGOL.

**Comment by steveoh** [comment]
Thanks for digging through that @MichaelAGRC.

@BGranberg or @brigsz, did someone ask us to set these up for desktop usage? I wish I could look at the logs to gain some insight but I cannot because the F5 doesn't have the logging module set up yet. 

Do you want to find some time to figure out what is up with these or do we shoot first and ask questions later by either converting them to WGS84 or removing them?

**Comment by BGranberg** [comment]
Given the limited usage, as long as we've thought through the key users (elections, leg, udot, sitla, maybe dnr?) i'd say we can let Mark Mitchell, Becky, Kate S., and Wade know what we are doing and why and then 'shoot' if we don't hear any quick objections

**Comment by brigsz** [comment]
The email has been sent out and if we don't hear back we will shut them down on August 31 2016

**Comment by brigsz** [comment]
Lets go ahead and shut these down today 8/25/2016.  I have contacted all we were concern about.  those that have responded don't believe these are relevant to them.

**Comment by stdavis** [comment]
I just shut them down.
